
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagementSystem.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class author_stats
{

    public int id { get; set; }

    public string author_name { get; set; }

    public Nullable<int> count_of_books { get; set; }

}

}
