//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public books()
        {
            this.events = new HashSet<events>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> categorie_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public string publication_year { get; set; }
        public string publisher { get; set; }
        public string number_of_page { get; set; }
        public Nullable<bool> situation { get; set; }
        public string image { get; set; }
        public string book_description { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<events> events { get; set; }
    }
}
