//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public events()
        {
            this.penalties = new HashSet<penalties>();
        }
    
        public int id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> personnel_id { get; set; }
        public Nullable<System.DateTime> get_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<System.DateTime> member_return_date { get; set; }
        public Nullable<bool> process_situation { get; set; }
    
        public virtual books books { get; set; }
        public virtual members members { get; set; }
        public virtual personnels personnels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<penalties> penalties { get; set; }
    }
}
